name: "setup environment"
description: "setup node.js and install dependencies"
runs:
  using: "composite"
  steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "22"
        cache: "npm"

    - name: install dependencies
      run: npm ci
      shell: bash
