name: linting, testing, building
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - name: Lint
        run: npm run lint
      - name: Lint css
        run: npm run lint-css

  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - name: Build project
        run: npm run build-prod

  unit-test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - name: Unit test
        run: npm run test-unit
